name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      #TF_LOG: TRACE
      ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
      ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -backend-config backend.conf
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible
      shell: bash

    - name: Run Ansible Playbook
      working-directory: ansible
      run: |
        ./deploy.sh